# -*- coding: utf-8 -*-
"""CV_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgLFAmSPIj9JqQuLQmTsvAo5rbQ19yMq
"""

from google.colab import drive
drive.mount('/content/drive')

import os

BASE_PATH = "/content/drive/MyDrive/CV_dataset"

IMAGE_DIR = os.path.join(BASE_PATH, "processed_dataset")

TRAIN_CSV = os.path.join(BASE_PATH, "train_split.csv")
TEST_CSV  = os.path.join(BASE_PATH, "test_split.csv")

## just check
os.listdir('/content/drive/MyDrive/CV_dataset')

import pandas as pd

train_df = pd.read_csv(TRAIN_CSV)
test_df  = pd.read_csv(TEST_CSV)

print(train_df.head())

train_df["full_path"] = train_df["image_path"].apply(
    lambda x: os.path.join(IMAGE_DIR, x)
)

test_df["full_path"] = test_df["image_path"].apply(
    lambda x: os.path.join(IMAGE_DIR, x)
)

## checking duplicates
print(train_df.duplicated().sum())
print(test_df.duplicated().sum())

## checking null
print(train_df.isnull().sum())
print(test_df.isnull().sum())

# load val_split data
VAL_CSV = os.path.join(BASE_PATH, "val_split.csv")

val_df = pd.read_csv(VAL_CSV)

val_df["full_path"] = val_df["image_path"].apply(
    lambda x: os.path.join(IMAGE_DIR, x)
)
# check duplicates and nulls
print(val_df.duplicated().sum())
print(val_df.isnull().sum())

import pandas as pd

# Number of Normal images to keep (these numbers are detected according to relative percentage between train, val and test images -> the target is to
## reduce normal images to 1200 for two reasons: first is that the total images took a very long time to be read so we want to reduce their count
## also, since the normal class has very large count relative to other classes so that make data imbalanced, so we choose normal class to reduce
##it to try to make data more balanced )
N_TRAIN_NORMAL = 840
N_TEST_NORMAL = 180
N_VAL_NORMAL = 180

# train
train_normal = train_df[train_df["label_name"] == "Normal"].sample(
    n=N_TRAIN_NORMAL,
    random_state=42
)

train_other = train_df[train_df["label_name"] != "Normal"]

train_df = pd.concat([train_normal, train_other], ignore_index=True)
train_df = train_df.sample(frac=1, random_state=42).reset_index(drop=True)

# test
test_normal = test_df[test_df["label_name"] == "Normal"].sample(
    n=N_TEST_NORMAL,
    random_state=42
)

test_other = test_df[test_df["label_name"] != "Normal"]

test_df = pd.concat([test_normal, test_other], ignore_index=True)
test_df = test_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Validation
val_normal = val_df[val_df["label_name"] == "Normal"].sample(
    n=N_VAL_NORMAL,
    random_state=42
)

val_other = val_df[val_df["label_name"] != "Normal"]

val_df = pd.concat([val_normal, val_other], ignore_index=True)
val_df = val_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Check counts
print("Train:")
print(train_df["label_name"].value_counts())

print("\nTest:")
print(test_df["label_name"].value_counts())

print("\nValidation:")
print(val_df["label_name"].value_counts())

print("\nTotal Normal images:",
      (train_df["label_name"] == "Normal").sum() +
      (test_df["label_name"] == "Normal").sum() +
      (val_df["label_name"] == "Normal").sum())

image_paths = train_df["full_path"].values
labels = train_df["label"].values

image_paths_test = test_df["full_path"].values
labels_test = test_df["label"].values

image_paths_val = val_df["full_path"].values
labels_val = val_df["label"].values

### checking numbers
print(image_paths.shape)
print(labels.shape)

print(image_paths_test.shape)
print(labels_test.shape)

print(image_paths_val.shape)
print(labels_val.shape)

## just for checking coresspondance
print(image_paths_test[510])
print(labels_test[510])

print(image_paths[2390])
print(labels[2390])

print(image_paths[0])
print(labels[0])

import cv2
import matplotlib.pyplot as plt

# Images to compare
selected_paths = [
    image_paths_test[510],
    image_paths[2390],
    image_paths[0]
]

plt.figure(figsize=(10, 12))

for i, path in enumerate(selected_paths):

    # Read original image
    original = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    # Resize to 128x128
    resized = cv2.resize(original, (128, 128), interpolation=cv2.INTER_AREA)

    # Enlarge resized image back to original size for visualization only
    resized_display = cv2.resize(
        resized,
        (384, 384),
        interpolation=cv2.INTER_NEAREST
    )

    # Original image
    plt.subplot(len(selected_paths), 2, 2*i + 1)
    plt.imshow(original, cmap='gray')
    plt.title(f"Original\n{original.shape}")
    plt.axis('off')

    # Resized image
    plt.subplot(len(selected_paths), 2, 2*i + 2)
    plt.imshow(resized_display, cmap='gray')
    plt.title(f"Resized to 128×128\n(Display only)")
    plt.axis('off')

plt.tight_layout()
plt.show()

## since the difference in above is acceptable and classes still reecognizable so we resized image size to 128*128 to make their reading faster and reduce feature numbers in future models
import cv2
import numpy as np

IMG_SIZE = 128 # fast processing
batch_size = 500

train_batches = []
train_label_batches = []

for start in range(0, len(image_paths), batch_size):
    end = min(start + batch_size, len(image_paths))

    batch_paths = image_paths[start:end]
    batch_labels = labels[start:end]

    batch_images = []

    for path in batch_paths:
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE), interpolation=cv2.INTER_AREA)  # shrink image
        batch_images.append(img)

    batch_images = np.array(batch_images)
    batch_labels = np.array(batch_labels)

    # Save this batch
    train_batches.append(batch_images)
    train_label_batches.append(batch_labels)

    print(batch_images.shape)

# Concatenate all training batches
X_train = np.concatenate(train_batches, axis=0)
y_train = np.concatenate(train_label_batches, axis=0)

print(X_train.shape)
print(y_train.shape)

import cv2
import numpy as np

IMG_SIZE = 128
batch_size = 500

test_batches = []
test_label_batches = []

for start in range(0, len(image_paths_test), batch_size):
    end = min(start + batch_size, len(image_paths_test))

    batch_paths = image_paths_test[start:end]
    batch_labels = labels_test[start:end]

    batch_images = []

    for path in batch_paths:
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE), interpolation=cv2.INTER_AREA)  # shrink image
        batch_images.append(img)

    batch_images = np.array(batch_images)
    batch_labels = np.array(batch_labels)

    # Save this batch
    test_batches.append(batch_images)
    test_label_batches.append(batch_labels)

    print(batch_images.shape)

# Concatenate all training batches
X_test = np.concatenate(test_batches, axis=0)
y_test = np.concatenate(test_label_batches, axis=0)

print(X_test.shape)
print(y_test.shape) #labels

import cv2
import numpy as np

IMG_SIZE = 128     # smaller size to be much faster to read and process
batch_size = 500

val_batches = []
val_label_batches = []

for start in range(0, len(image_paths_val), batch_size):
    end = min(start + batch_size, len(image_paths_val))

    batch_paths = image_paths_val[start:end]
    batch_labels = labels_val[start:end]

    batch_images = []

    for path in batch_paths:
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE), interpolation=cv2.INTER_AREA)  # shrink image
        batch_images.append(img)

    batch_images = np.array(batch_images)
    batch_labels = np.array(batch_labels)

    val_batches.append(batch_images)
    val_label_batches.append(batch_labels)

    print(batch_images.shape)

X_val = np.concatenate(val_batches, axis=0)
y_val = np.concatenate(val_label_batches, axis=0)

print(X_val.shape)
print(y_val.shape)

## normalize

X_train = X_train.astype(np.float32) / 255.0
X_test = X_test.astype(np.float32) / 255.0
X_val = X_val.astype(np.float32) / 255.0

## Model 1 (Random Forest)  -> Machine Learning

## first flatten
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

print(X_train_flat.shape)
print(X_test_flat.shape)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True],
    'max_samples': [0.6, 0.8, 1.0]
}

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,
    cv=2,
    scoring='accuracy',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

print("Searching for best Random Forest parameters...")
random_search.fit(X_train_flat, y_train)

print("\nBest Parameters:")
print(random_search.best_params_)

best_model = random_search.best_estimator_

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sb

# Predict on the test set
y_pred = best_model.predict(X_test_flat)

# Accuracy
acc = accuracy_score(y_test, y_pred) * 100
print(f"Final Accuracy of the Best Model: {acc:.2f}%")

# Classification Report
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Ischemia", "Bleeding"]
))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sb.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=["Normal", "Ischemia", "Bleeding"],
    yticklabels=["Normal", "Ischemia", "Bleeding"]
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - Random Forest")
plt.show()

## Another Version with PCA to compare results
from sklearn.decomposition import PCA

# Keep 95% of the information
pca = PCA(n_components=0.95, random_state=42)

X_train_pca = pca.fit_transform(X_train_flat)
X_test_pca = pca.transform(X_test_flat)

print("Original shape:", X_train_flat.shape)
print("After PCA:", X_train_pca.shape)
print("Number of principal components:", pca.n_components_)

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True],
    'max_samples': [0.6, 0.8, 1.0]
}

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,
    cv=2,
    scoring='accuracy',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

print("Searching for best Random Forest parameters...")
random_search.fit(X_train_pca, y_train)

print("\nBest Parameters:")
print(random_search.best_params_)

best_model = random_search.best_estimator_

# Predict on the test set
y_pred = best_model.predict(X_test_pca)

# Accuracy
acc = accuracy_score(y_test, y_pred) * 100
print(f"Final Accuracy of the Best Model: {acc:.2f}%")

# Classification Report
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Ischemia", "Bleeding"]
))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sb.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=["Normal", "Ischemia", "Bleeding"],
    yticklabels=["Normal", "Ischemia", "Bleeding"]
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - Random Forest")
plt.show()

## SVM Model

from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

# Parameter search space
param_dist = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto', 0.01, 0.001]
}

svm = SVC(random_state=42)

random_search = RandomizedSearchCV(
    estimator=svm,
    param_distributions=param_dist,
    n_iter=10,
    cv=2,
    scoring='accuracy',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

print("Searching for best SVM parameters...")

random_search.fit(X_train_pca, y_train)

print("\nBest Parameters:")
print(random_search.best_params_)

best_model = random_search.best_estimator_

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sb

y_pred = best_model.predict(X_test_pca)

acc = accuracy_score(y_test, y_pred)

print(f"Accuracy: {acc*100:.2f}%")

print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Ischemia", "Bleeding"]
))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))

sb.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=["Normal", "Ischemia", "Bleeding"],
    yticklabels=["Normal", "Ischemia", "Bleeding"]
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - SVM")

plt.show()

## to see effect of PCA on SVM, let's do a model without PCA
## SVM Model (Without PCA)

# Parameter search space
param_dist = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto', 0.01, 0.001]
}

# Initialize SVM
svm = SVC(random_state=42)

# Randomized Search
random_search = RandomizedSearchCV(
    estimator=svm,
    param_distributions=param_dist,
    n_iter=10,
    cv=2,
    scoring='accuracy',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

print("Searching for best SVM parameters...")

# Use flattened images
random_search.fit(X_train_flat, y_train)

print("\nBest Parameters:")
print(random_search.best_params_)

# Best model
best_model = random_search.best_estimator_

# Predict on test set
y_pred = best_model.predict(X_test_flat)

# Accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc*100:.2f}%")

# Classification report
print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Ischemia", "Bleeding"]
))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sb.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=["Normal", "Ischemia", "Bleeding"],
    yticklabels=["Normal", "Ischemia", "Bleeding"]
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - SVM (Without PCA)")
plt.show()

#### Deep Learning Models
import numpy as np

# Convert grayscale to 3-channel for EfficientNetB0
X_train_rgb = np.repeat(X_train[..., np.newaxis], 3, axis=-1)  # (N,128,128,3)
X_val_rgb   = np.repeat(X_val[..., np.newaxis], 3, axis=-1)
X_test_rgb  = np.repeat(X_test[..., np.newaxis], 3, axis=-1)

print(X_train_rgb.shape, X_val_rgb.shape, X_test_rgb.shape)

from tensorflow.keras.applications.efficientnet import preprocess_input


X_train_eff = preprocess_input(X_train_rgb * 255.0)
X_val_eff   = preprocess_input(X_val_rgb * 255.0)
X_test_eff  = preprocess_input(X_test_rgb * 255.0)

## Model 3 (EfficientNetB0)
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, models

#building model
base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(128,128,3))
base_model.trainable = False  # freeze for stage 1

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')  # 3 classes: Normal, Ischemic, Hemorrhagic
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# train stage 1 with early stopping using the val set
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# save the best stage-1 model to disk, so fine-tuning can never lose it
checkpoint_stage1 = ModelCheckpoint(
    'best_stage1_model.keras',
    monitor='val_loss',
    save_best_only=True
)
history = model.fit(
    X_train_eff, y_train,
    validation_data=(X_val_eff, y_val),
    epochs=20,
    batch_size=16,
    callbacks=[early_stop, checkpoint_stage1]
)

import tensorflow as tf

# stage 2 (unfreaze top layers and then doing fine-tune)
base_model.trainable = True

# freeze all but the last approx 30 layers
for layer in base_model.layers[:-30]:
    layer.trainable = False

# BatchNorm layers store stable average values learned from millions of ImageNet images.
# If left trainable, they will recalculate those averages using only our small CT scan batches,
# which can corrupt good pretrained values instead of improving them.
# So even within the last 30 unfrozen layers, force any BatchNorm layer to stay frozen.

for layer in base_model.layers[-30:]:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

checkpoint_stage2 = ModelCheckpoint(
    'best_stage2_model.keras',
    monitor='val_loss',
    save_best_only=True
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    X_train_eff, y_train,
    validation_data=(X_val_eff, y_val),
    epochs=10,
    batch_size=16,
    callbacks=[early_stop, checkpoint_stage2]
)

# pick whichever stage actually performed better on val_loss
best_stage1_val_loss = min(history.history['val_loss'])
best_stage2_val_loss = min(history_fine.history['val_loss'])

print("Best stage 1 val_loss:", best_stage1_val_loss)
print("Best stage 2 val_loss:", best_stage2_val_loss)

if best_stage2_val_loss < best_stage1_val_loss:
    print("Using fine-tuned model (stage 2)")
    final_model = tf.keras.models.load_model('best_stage2_model.keras')
else:
    print("Using frozen-backbone model (stage 1) — fine-tuning did not improve results")
    final_model = tf.keras.models.load_model('best_stage1_model.keras')

from sklearn.metrics import classification_report, confusion_matrix, f1_score

import numpy as np

# model predictions on the test set
y_pred_probs = final_model.predict(X_test_eff)
y_pred = np.argmax(y_pred_probs, axis=1) # convert probabilities to class labels

# overall accuracy
test_loss, test_acc = final_model.evaluate(X_test_eff, y_test)
print("Test accuracy:", test_acc)

# F1 score
f1_macro = f1_score(y_test, y_pred, average='macro')
print("F1 score:", f1_macro)

# precision, recall, F1 per class
# support is for the number of the actual samples
print(classification_report(y_test, y_pred, target_names=['Normal', 'Ischemic', 'Hemorrhagic']))
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix:")
print(cm)

## Model: ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# preprocess (reuse the *_rgb arrays already built for EfficientNet)
X_train_res = resnet_preprocess(X_train_rgb * 255.0)
X_val_res   = resnet_preprocess(X_val_rgb * 255.0)
X_test_res  = resnet_preprocess(X_test_rgb * 255.0)

# build model
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(128,128,3))
base_model.trainable = False  # stage 1: frozen backbone

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# Stage 1 training
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
checkpoint_stage1 = ModelCheckpoint('best_resnet_stage1.keras', monitor='val_loss', save_best_only=True)

history = model.fit(
    X_train_res, y_train,
    validation_data=(X_val_res, y_val),
    epochs=20,
    batch_size=16,
    callbacks=[early_stop, checkpoint_stage1]
)

# Stage 2: unfreeze top layers, fine-tune
base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

for layer in base_model.layers[-30:]:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

checkpoint_stage2 = ModelCheckpoint('best_resnet_stage2.keras', monitor='val_loss', save_best_only=True)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    X_train_res, y_train,
    validation_data=(X_val_res, y_val),
    epochs=10,
    batch_size=16,
    callbacks=[early_stop, checkpoint_stage2]
)

# pick best stage
best_stage1_val_loss = min(history.history['val_loss'])
best_stage2_val_loss = min(history_fine.history['val_loss'])

if best_stage2_val_loss < best_stage1_val_loss:
    print("Using fine-tuned model (stage 2)")
    final_model = tf.keras.models.load_model('best_resnet_stage2.keras')
else:
    print("Using frozen-backbone model (stage 1)")
    final_model = tf.keras.models.load_model('best_resnet_stage1.keras')

# evaluation
from sklearn.metrics import classification_report, confusion_matrix, f1_score
import numpy as np

y_pred_probs = final_model.predict(X_test_res)
y_pred = np.argmax(y_pred_probs, axis=1)

test_loss, test_acc = final_model.evaluate(X_test_res, y_test)
print("Test accuracy:", test_acc)

f1_macro = f1_score(y_test, y_pred, average='macro')
print("F1 score:", f1_macro)

print(classification_report(y_test, y_pred, target_names=['Normal', 'Ischemic', 'Hemorrhagic']))
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix:")
print(cm)