name: Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome"

      - name: Checkout repo
        uses: actions/checkout@4.2.2

      - name: List repo files
        run: ls -la
